### ISSUE TITLE
Make jest-it-up only increase coverage thresholds only to master (or specified) branch

### ISSUE THREAD

**Issue by djErock** [rbardini/jest-it-up#15]
Probably more of an enhancement request but here goes:

REQUEST:
Is there any way to add to the config to have jest-it-up only make adjustments to the master branch (or any specified set of branches)?

Was thinking that it could check the branch name or commits for the word master or something to that degree.

USE CASE:
We have a develop branch that serves as more of a playground and sometimes need to get code up quickly for integration testing as well as asynchronous unit/automation test writing while in a live ENV.

Could this be added or is there any unforeseen negative outcome to doing this?

Thanks

**Comment by rbardini** [comment]
Hi @djErock! That sounds like a common use case. However, I don't think it should be a responsibility of this library. You can achieve this by combining jest-it-up with [git-branch-is](https://github.com/kevinoid/git-branch-is), for example:

```json
{
  "posttest": "git-branch-is master && jest-it-up"
}
```
