### ISSUE TITLE
Rounding?

### ISSUE THREAD

**Issue by Twipped** [rbardini/jest-it-up#17]
I'd like to have it only bump coverage numbers down to the nearest whole value. Is there an option for this that I'm not seeing? Threshold appears to still set it to the thousandths place once you cross the threshold.

We're having a lot of issues with merge conflicts on the jest config because the coverage values change for every single PR.

**Comment by rbardini** [comment]
There's no option for rounding. Maybe a reasonable default (e.g. two digits) would be enough?

**Comment by aschillio** [comment]
I have the exact same issue, any workaround on this ?

**Comment by rbardini** [comment]
A workaround is to define a higher `margin`, so that thresholds are only increased when they go above that value.
