### ISSUE TITLE
Minor Bug: `coverageDirectory` set to `"<rootDir>/coverage"` results in Error: `ENOENT: no such file or directory`

### ISSUE THREAD

**Issue by tjunghans** [rbardini/jest-it-up#22]
Hi @rbardini 

This is a useful plugin, thank you!

I noticed that configuring `coverageDirectory` to be `coverageDirectory: "<rootDir>/coverage"` results in an `ENOENT` error because [<rootDir>](https://jestjs.io/docs/configuration#rootdir-string) is not parsed. The following value works `"./coverage"`.

Regards,
TJ

**Comment by anlesk** [comment]
^ having the same issue
