### ISSUE TITLE
Read coverage dir path from jest config

### ISSUE THREAD

**Issue by juzerzarif** [rbardini/jest-it-up#4]
The coverage directory is hard coded to look at `cwd/coverage` currently. This doesn't allow for custom coverage directory locations which is something that jest allows via its config. I see the config is already being read here https://github.com/rbardini/jest-it-up/blob/master/lib/getData.js#L4 so the `coverageDirectory` option could just be read from there (defaulting to the cwd/coverage if undefined).

In the same vein, it would also be nice to have the ability to provide a custom jest config path.

I'd be willing to put up a PR if this is something you'd be cool with supporting 😇.

**Comment by rbardini** [comment]
Hi @juzerzarif! I agree with both suggestions. For the custom config path, we could offer the same `-c, --config <path>` option that [Jest CLI uses](https://jestjs.io/docs/en/cli#--configpath).

PRs would be welcome (preferably separate), so feel free to submit yours 😉
