### ISSUE TITLE
When using jest-it-up as a reporter in Jenkins file, throws TypeError, Not a constructor

### ISSUE THREAD

**Issue by Adtya11** [rbardini/jest-it-up#8]
- `11:55:37  > event-widgets@1.8.1086 test /build/workspace/oslo_event-ui_PR-18096/pkgs/event-widgets
- 11:55:37  > TZ=Pacific/Tongatapu BABEL_ENV=node jest "--maxWorkers=30%" "--reporters=default" "--reporters=jest-it-up"
- 11:55:37  
- 11:55:38  > TypeError: An error occurred while adding the reporter at path "/build/workspace/oslo_event-ui_PR-18096/node_modules/.pnpm/jest-it-up@2.0.0/node_modules/jest-it-up/lib/index.js".Reporter is not a constructor`

Not sure but module is exported as an arrow function thus it might be not able to initialise with new !

**Comment by rbardini** [comment]
Hi @Adtya11! jest-it-up is not supposed to be used as a Jest reporter, but as a standalone CLI tool, which you run once your tests finish. It then reads the (JSON) coverage report to determine new thresholds.

This means you must:

1. enable `json-summary` coverage reporter in Jest configuration;
2. run `jest-it-up` after your test script.

Please refer to the [documentation](https://github.com/rbardini/jest-it-up#usage) for more details.

**Comment by Adtya11** [comment]
Thanks for telling @rbardini
